stages:
  - deploy

development:
  stage: deploy
  
  script:
    - "/opt/python/bin/python ./ce_installer/ce_installer.py --root ceroot --env dev"

  tags:
    - HPC-dev

test:
  stage: deploy
  
  script:
    - "/opt/python/bin/python ./ce_installer/ce_installer.py --root ceroot --env test"

  tags:
    - HPC-test