stages:
  - deploy

development:
  stage: deploy
  
  script:
    - pwd>/data/development.txt

  tags:
    - HPC-dev

test:
  stage: deploy
  
  script:
    - cd ~
    - touch test

  tags:
    - HPC-test