stages:
  - deploy

development:
  stage: deploy
  
  script:
    - "/opt/python/bin/python ./ce_installer/ce_installer.py --root ceroot --env dev"
  
  only:
    - development

  tags:
    - HPC-dev
  
  artifacts:
    - dirty.txt

test:
  stage: deploy
  
  script:
    - "/opt/python/bin/python ./ce_installer/ce_installer.py --root ceroot --env test"

  only:
    - test
  
  tags:
    - HPC-test

  artifacts:
    - dirty.txt