stages:
  - deploy

development:
  stage: deploy
  script:
    - cd /data/
    - touch development

  only:
    - development

  tags:
    - HPC-dev

test:
  stage: deploy
  script:
    - cd ~
    - touch test

  only:
    - test

  tags:
    - HPC-test